"""initial schema

Revision ID: 5f916f995ae0
Revises: 
Create Date: 2026-09-22 15:59:39.752297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f916f995ae0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('act_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_ro', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('act_type_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['act_type_id'], ['act_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_document_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('act_type_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_ro', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('classification_hints', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['act_type_id'], ['act_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_required_document_types_act_type_code', 'required_document_types', ['act_type_id', 'code'], unique=True)
    op.create_table('checklist_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('required_document_type_id', sa.String(), nullable=False),
    sa.Column('override_status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('set_by', sa.String(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['required_document_type_id'], ['required_document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checklist_overrides_case_required_type_set_at', 'checklist_overrides', ['case_id', 'required_document_type_id', 'set_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('matched_required_document_type_id', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['matched_required_document_type_id'], ['required_document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('predicted_required_document_type_id', sa.String(), nullable=True),
    sa.Column('predicted_type_code_raw', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alternative_type_code_raw', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('raw_response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['predicted_required_document_type_id'], ['required_document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('classification_result_id', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('prior_matched_required_document_type_id', sa.String(), nullable=True),
    sa.Column('final_matched_required_document_type_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classification_result_id'], ['classification_results.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['final_matched_required_document_type_id'], ['required_document_types.id'], ),
    sa.ForeignKeyConstraint(['prior_matched_required_document_type_id'], ['required_document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_reviews_final_matched_required_document_type_id', 'document_reviews', ['final_matched_required_document_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_reviews_final_matched_required_document_type_id', table_name='document_reviews')
    op.drop_table('document_reviews')
    op.drop_table('classification_results')
    op.drop_table('documents')
    op.drop_index('ix_checklist_overrides_case_required_type_set_at', table_name='checklist_overrides')
    op.drop_table('checklist_overrides')
    op.drop_index('ix_required_document_types_act_type_code', table_name='required_document_types')
    op.drop_table('required_document_types')
    op.drop_table('cases')
    op.drop_table('act_types')
    # ### end Alembic commands ###
